# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 网站
title: 小车的菜园子
subtitle: ''
description: '记录小车快乐的学习之旅'
keywords: blog
author: hbche
language: zh-CN
timezone: Asia/Shanghai

# 网址
## 在这里设置你的网站网址. 例如, 如果你使用的是 GitHub Page, 设置的网址形式形如 'https://username.github.io/project'
url: http://example.com
root:
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # 是否在永久链接中保留尾部的 index.html，设置为 false 时去除，默认值为 true
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# 目录
source_dir: source # 资源文件夹，这个文件夹用来存放内容。
public_dir: public # 公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags # 标签文件夹
archive_dir: archives # 归档文件夹
category_dir: categories # 分类文件夹
code_dir: downloads/code
i18n_dir: :lang # 国际化（i18n）文件夹
skip_render: # 跳过指定文件的渲染。匹配到的文件将会被不做改动地复制到 public 目录中。您可使用 glob 表达式来匹配路径。

# 文章编写
new_post_name: :title.md # 新文章的文件名称
default_layout: post # 预设布局
auto_spacing: true # 在中文和英文之间加入空格 默认false
titlecase: false # 把标题转换为 title case
external_link: # 在新标签中打开链接
  enable: true # 在新标签中打开链接
  field: site # 对整个网站（site）生效或仅对文章（post）生效
  exclude: '' # 需要排除的域名。主域名和子域名如 www 需分别配置
filename_case: 0 # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false # 显示草稿
post_asset_folder: false # 启动 Asset 文件夹
relative_link: false # 把链接改为与根目录的相对位址
future: true # 显示未来的文章
highlight: # 代码块的设置, 请参考 Highlight.js 进行设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs: # 代码块的设置, 请参考 PrismJS 进行设置
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类 & 标签
default_category: uncategorized # 默认分类
category_map: # 分类别名
tag_map: # 标签别名

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo 使用 Moment.js 来解析和显示时间。
## 你可以按照momentjs中定义的格式化自定义日期格式化
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD # 日期格式化
time_format: HH:mm:ss # 时间格式化
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime' # 使用文件的最后修改时间。这是从 Hexo 3.0.0 开始的默认行为。

# 分页
## Set per_page to 0 to disable pagination
per_page: 10 # 每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page # 分页目录

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# 扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: maupassant

# 部署
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/hbche/hbche.github.io
  # example, https://github.com/hexojs/hexojs.github.io
  branch: gh-pages
